
-- Admin users table (company admin)
CREATE TABLE public.admins (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  email TEXT UNIQUE NOT NULL,
  password_hash TEXT NOT NULL,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

-- Seed default admin (password: 987)
INSERT INTO public.admins (email, password_hash) VALUES ('admin987@gmail.com', '987');

-- Platforms table - single source of truth for all teacher platforms
CREATE TABLE public.platforms (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  code TEXT UNIQUE NOT NULL, -- e.g. R-9847
  slug TEXT UNIQUE NOT NULL, -- e.g. ahmed-math for /m/ahmed-math
  teacher_name TEXT NOT NULL,
  teacher_phone TEXT NOT NULL,
  subject TEXT NOT NULL, -- math, science, arabic, studies, english
  stage TEXT NOT NULL,   -- prep, secondary, primary
  grade_levels JSONB NOT NULL DEFAULT '[]'::jsonb, -- ["1-prep","2-prep","3-prep"]
  template_tier TEXT NOT NULL DEFAULT 'normal', -- normal | pro
  package_students INTEGER NOT NULL DEFAULT 50,
  package_price INTEGER NOT NULL DEFAULT 500,
  config JSONB NOT NULL DEFAULT '{}'::jsonb, -- colors, icons, animations, name, logo, ai-generated customizations
  status TEXT NOT NULL DEFAULT 'pending', -- pending | approved | active | paused | rejected
  payment_status TEXT NOT NULL DEFAULT 'unpaid', -- unpaid | paid | overdue
  admin_notes TEXT,
  platform_admin_email TEXT, -- teacher's admin email for their platform
  platform_admin_password TEXT, -- simple stored for MVP
  created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  approved_at TIMESTAMPTZ,
  updated_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE INDEX idx_platforms_slug ON public.platforms(slug);
CREATE INDEX idx_platforms_status ON public.platforms(status);

-- Student access codes (generated by platform admin/teacher)
CREATE TABLE public.student_codes (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  platform_id UUID NOT NULL REFERENCES public.platforms(id) ON DELETE CASCADE,
  code TEXT NOT NULL,
  is_used BOOLEAN NOT NULL DEFAULT false,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  UNIQUE(platform_id, code)
);

-- Students registered on platforms
CREATE TABLE public.students (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  platform_id UUID NOT NULL REFERENCES public.platforms(id) ON DELETE CASCADE,
  access_code TEXT NOT NULL,
  full_name TEXT NOT NULL,
  phone TEXT NOT NULL,
  grade_level TEXT NOT NULL,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  UNIQUE(platform_id, access_code)
);

CREATE INDEX idx_students_platform ON public.students(platform_id);

-- Content table (videos, pdfs, questions, exams)
CREATE TABLE public.content (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  platform_id UUID NOT NULL REFERENCES public.platforms(id) ON DELETE CASCADE,
  kind TEXT NOT NULL, -- video | pdf | question | exam
  title TEXT NOT NULL,
  grade_level TEXT NOT NULL,
  unit TEXT,
  lesson TEXT,
  data JSONB NOT NULL DEFAULT '{}'::jsonb, -- url, options, correct_answer, etc
  created_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE INDEX idx_content_platform ON public.content(platform_id);
CREATE INDEX idx_content_kind ON public.content(kind);

-- Exam results
CREATE TABLE public.exam_results (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  platform_id UUID NOT NULL REFERENCES public.platforms(id) ON DELETE CASCADE,
  student_id UUID NOT NULL REFERENCES public.students(id) ON DELETE CASCADE,
  exam_id UUID NOT NULL REFERENCES public.content(id) ON DELETE CASCADE,
  score INTEGER NOT NULL DEFAULT 0,
  total INTEGER NOT NULL DEFAULT 0,
  answers JSONB NOT NULL DEFAULT '{}'::jsonb,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

-- Enable RLS
ALTER TABLE public.admins ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.platforms ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.students ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.content ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.student_codes ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.exam_results ENABLE ROW LEVEL SECURITY;

-- Public read policies (for MVP: we handle auth in app logic since admin is single hardcoded account)
-- Platforms: anyone can view approved/active platforms (needed for public /m/:slug)
CREATE POLICY "Public can view approved platforms" ON public.platforms
  FOR SELECT USING (status IN ('approved','active','paused'));

CREATE POLICY "Anyone can submit a platform request" ON public.platforms
  FOR INSERT WITH CHECK (true);

-- For MVP admin actions go through edge functions with service role; also allow anon update for simplicity
CREATE POLICY "Anyone can update platforms (MVP)" ON public.platforms
  FOR UPDATE USING (true);

-- Students: anyone can register; anyone on platform can view (MVP)
CREATE POLICY "Public can insert students" ON public.students
  FOR INSERT WITH CHECK (true);
CREATE POLICY "Public can view students" ON public.students
  FOR SELECT USING (true);
CREATE POLICY "Public can delete students" ON public.students
  FOR DELETE USING (true);

-- Content: public read for active platforms, public write (MVP - teacher admin UI)
CREATE POLICY "Public can view content" ON public.content
  FOR SELECT USING (true);
CREATE POLICY "Public can insert content" ON public.content
  FOR INSERT WITH CHECK (true);
CREATE POLICY "Public can delete content" ON public.content
  FOR DELETE USING (true);
CREATE POLICY "Public can update content" ON public.content
  FOR UPDATE USING (true);

-- Student codes
CREATE POLICY "Public can view student codes" ON public.student_codes
  FOR SELECT USING (true);
CREATE POLICY "Public can insert student codes" ON public.student_codes
  FOR INSERT WITH CHECK (true);
CREATE POLICY "Public can update student codes" ON public.student_codes
  FOR UPDATE USING (true);
CREATE POLICY "Public can delete student codes" ON public.student_codes
  FOR DELETE USING (true);

-- Exam results
CREATE POLICY "Public can insert exam results" ON public.exam_results
  FOR INSERT WITH CHECK (true);
CREATE POLICY "Public can view exam results" ON public.exam_results
  FOR SELECT USING (true);

-- Admins: used only via edge function with service role, no public access
CREATE POLICY "No public access to admins" ON public.admins
  FOR SELECT USING (false);

-- Update trigger
CREATE OR REPLACE FUNCTION public.set_updated_at()
RETURNS TRIGGER AS $$
BEGIN
  NEW.updated_at = now();
  RETURN NEW;
END;
$$ LANGUAGE plpgsql;

CREATE TRIGGER platforms_updated_at
  BEFORE UPDATE ON public.platforms
  FOR EACH ROW EXECUTE FUNCTION public.set_updated_at();
